### ISSUE TITLE
Namespace 'YT' has no exported member 'EventArgs'

### ISSUE THREAD

**Issue by dwploc** [orizens/ngx-youtube-player#12]
During compile on Angular 4.0.1
service.d.ts and component.d.ts

added @types/youtube
now get -
/node_modules/ng2-youtube-player/src/youtube-player.service.d.ts (6,30): Namespace 'YT' has no exported member 'EventArgs'.

**Comment by capitola-dev** [comment]
+1

**Comment by stuarthallows** [comment]
Create a new Angular 4 project (I used the CLI) and add `ng2-youtube-player` version 0.0.2. On build the error is;

    Cannot find namespace 'YT'
    Cannot find type definition file for 'youtube'

So add package `@types/youtube`, on build the error is then;

     Namespace 'YT' has no exported member 'EventArgs'

**Comment by julienR2** [comment]
+1

**Comment by brainydevs** [comment]
+1
It seems that `EventArgs` is no longer present in `@types/youtube@0.0.29`

**Comment by dwploc** [comment]
Oren, first appreciate your work.  Good solution to easily add yt to an app.
Just a clarification, does the v0.3 label mean these will be fixed when you commit changes to that version?

Using your module in a web app I'm building for our church.

Dave

**Comment by dwploc** [comment]
Oops,wrong button

**Comment by orizens** [comment]
Hi @dwploc
Yes, this will be fixed in to next version
